### ISSUE TITLE
Force Browser Refresh

### ISSUE THREAD

**Issue by boxyoman** [HopeCommunityChurch/project-2-15#36]
Most people probably won't close and open the editor when there is an update leaving them with an older version of the editor. We should have the website refresh when it detects there's a new version.

**Comment by NuclearKev** [comment]
Does the editor throw any chunk-related errors when there is an update?

**Comment by boxyoman** [comment]
I don't know what you mean by that.

**Comment by boxyoman** [comment]
@NuclearKev the method you want to use is HEAD. If you don’t have time to do this soon, I’ll probably just do it.
